import { useMemo, useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { api, type ReportDaily, type ReportRisk, type ReportWeekly } from '../api/client';
import { EmptyState, LoadingSpinner, OfflineState, StatusPill } from '../components/LoaderStates';
import { formatRelativeTime } from '../lib/time';
import { useTimedResource } from '../lib/useTimedResource';
import { useStore } from '../store/useStore';

type ReportKey = 'daily' | 'weekly' | 'risk';

const reportLoaders: Record<ReportKey, (params?: Record<string, unknown>) => Promise<ReportDaily | ReportWeekly | ReportRisk>> = {
  daily: api.getDailyReport,
  weekly: api.getWeeklyReport,
  risk: api.getRiskReport,
};

const getTimelineCoverage = (timeline: string) => {
  // Real index mapping
  const monthsReal = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  const parts = timeline.split('-');
  if (parts.length === 2) {
    const year = parseInt(parts[0], 10);
    const m = parseInt(parts[1], 10);
    const monthName = monthsReal[m - 1];
    const daysInMonth = new Date(year, m, 0).getDate();
    return `Reporting Period: ${monthName} ${year} (${monthName} 1 – ${monthName} ${daysInMonth})`;
  }
  return `Reporting Period: ${timeline}`;
};

function generatePdf(reportKey: ReportKey, data: ReportDaily | ReportWeekly | ReportRisk) {
  const doc = new jsPDF();
  const city = 'Bengaluru';
  const title =
    reportKey === 'daily' ? 'Monthly Summary Command Brief' : reportKey === 'weekly' ? 'Weekly Breakdown Intelligence' : 'Risk Analysis Report';
  const generatedAt = 'generatedAt' in data ? data.generatedAt : new Date().toISOString();
  const activeTimeline = useStore.getState().activeTimeline;

  doc.setFontSize(18);
  doc.text(`ParkSense`, 14, 16);
  doc.setFontSize(11);
  doc.text(city, 14, 23);
  doc.setFontSize(16);
  doc.text(title, 14, 34);
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 41);
  doc.text(`Timeline Period: ${activeTimeline}`, 14, 48);

  let cursorY = 54;

  const addSectionTitle = (text: string) => {
    doc.setFontSize(12);
    doc.text(text, 14, cursorY);
    cursorY += 4;
  };

  const addKeyValueTable = (rows: [string, string | number][]) => {
    autoTable(doc, {
      startY: cursorY,
      head: [['Metric', 'Value']],
      body: rows.map(([key, value]) => [key, String(value)]),
      theme: 'grid',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [17, 24, 39] },
    });
    cursorY = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? cursorY + 20;
    cursorY += 8;
  };

  if ('type' in data) {
    addKeyValueTable([
      ['Report Type', data.type],
      ['Generated At', generatedAt],
      ['Dataset Window', 'datasetWindow' in data ? data.datasetWindow : 'N/A'],
    ]);
  }

  if (reportKey === 'daily' && 'topHotspots' in data) {
    addSectionTitle('Top Hotspots');
    autoTable(doc, {
      startY: cursorY,
      head: [['Hotspot', 'Violations', 'Risk Score']],
      body: data.topHotspots.map((item) => [item.name, String(item.violations), item.riskScore.toFixed(1)]),
      theme: 'grid',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [17, 24, 39] },
    });
    cursorY = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? cursorY + 20;
  } else if (reportKey === 'weekly' && 'trend' in data) {
    addSectionTitle('Weekly Trend');
    autoTable(doc, {
      startY: cursorY,
      head: [['Date', 'Violations']],
      body: data.trend.map((item) => [item.date, String(item.violations)]),
      theme: 'grid',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [17, 24, 39] },
    });
    cursorY = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? cursorY + 20;
  } else if (reportKey === 'risk' && 'predictedHotspotsNext24h' in data) {
    addSectionTitle('Predicted Hotspots');
    autoTable(doc, {
      startY: cursorY,
      head: [['Hotspot', 'Predicted Risk']],
      body: data.predictedHotspotsNext24h.map((item) => [item.name, `${item.predictedRisk.toFixed(1)}%`]),
      theme: 'grid',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [17, 24, 39] },
    });
    cursorY = (doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? cursorY + 20;
  }

  doc.setFontSize(9);
  doc.text('Generated by ParkSense Traffic Intelligence Platform', 14, 285);
  doc.save(`parksense_${reportKey}_${activeTimeline}.pdf`);
}

export function ReportsCenter() {
  const [reportKey, setReportKey] = useState<ReportKey>('daily');
  const activeTimeline = useStore((state) => state.activeTimeline);
  const [sessionGeneratedTime, setSessionGeneratedTime] = useState<number>(Date.now());
  
  const { data, loading, timedOut, error, refresh } = useTimedResource(async () => {
    const res = await reportLoaders[reportKey]({ timeline: activeTimeline });
    setSessionGeneratedTime(Date.now());
    return res;
  }, [reportKey, activeTimeline]);

  const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle');

  const copyText = useMemo(() => JSON.stringify(data, null, 2), [data]);

  const copyReport = async () => {
    await navigator.clipboard.writeText(copyText);
    setCopyState('copied');
    window.setTimeout(() => setCopyState('idle'), 1500);
  };

  if (loading) return <LoadingSpinner />;
  if (timedOut) return <OfflineState message="Reports are taking too long to load." onAction={refresh} />;
  if (error) return <OfflineState message={error} onAction={refresh} />;
  if (!data) return <EmptyState message="No report payload returned by the backend." />;

  return (
    <div className="space-y-6">
      <div className="section-heading">
        <div>
          <div className="eyebrow">System reports</div>
          <h1>Reports Center</h1>
        </div>
        <div className="section-meta">
          <StatusPill tone="neutral" label={`Updated ${formatRelativeTime(new Date(sessionGeneratedTime).toISOString())}`} />
          <button type="button" className="btn btn--ghost" onClick={refresh}>
            Refresh
          </button>
        </div>
      </div>

      <div style={{ padding: '8px 16px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '8px', fontSize: '0.85rem', color: '#94a3b8', display: 'inline-block' }}>
        {getTimelineCoverage(activeTimeline)}
      </div>

      <div className="filter-row">
        {(['daily', 'weekly', 'risk'] as const).map((key) => (
          <button key={key} type="button" className={reportKey === key ? 'filter-pill active' : 'filter-pill'} onClick={() => setReportKey(key)}>
            {key === 'daily' ? 'Monthly Summary' : key === 'weekly' ? 'Weekly Breakdown' : 'Risk Analysis'}
          </button>
        ))}
      </div>

      <section className="panel-card">
        <div className="panel-card__header">
          <div>
            <h2>{reportKey === 'daily' ? 'Monthly Summary Command Brief' : reportKey === 'weekly' ? 'Weekly Breakdown Intelligence' : 'Risk Analysis Report'}</h2>
            <span className="muted-text">Content is rendered from the backend response only.</span>
          </div>
          <div className="flex gap-2">
            <button type="button" className="btn btn--ghost" onClick={copyReport}>
              {copyState === 'copied' ? 'Copied' : 'Copy report'}
            </button>
            <button type="button" className="btn btn--amber" onClick={() => generatePdf(reportKey, data)}>
              Download PDF
            </button>
          </div>
        </div>

        <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {'type' in data && (
            <div className="stat-mini">
              <span>Report type</span>
              <strong>{data.type}</strong>
            </div>
          )}
          <div className="stat-mini">
            <span>Generated at</span>
            <strong>{new Date(sessionGeneratedTime).toLocaleString()}</strong>
          </div>
          {'totalViolations' in data && (
            <div className="stat-mini">
              <span>Total violations</span>
              <strong>{data.totalViolations.toLocaleString()}</strong>
            </div>
          )}
          {'officerDeploymentSummary' in data && (
            <div className="stat-mini">
              <span>Active officers</span>
              <strong>{data.officerDeploymentSummary.activeOfficers}</strong>
            </div>
          )}
          {'officerUtilization' in data && (
            <div className="stat-mini">
              <span>Officer utilization</span>
              <strong>{data.officerUtilization.toFixed(1)}%</strong>
            </div>
          )}
          {'forecastHorizon' in data && (
            <div className="stat-mini">
              <span>Forecast horizon</span>
              <strong>{data.forecastHorizon}</strong>
            </div>
          )}
          {'criticalAlerts' in data && (
            <div className="stat-mini">
              <span>Critical alerts</span>
              <strong>{data.criticalAlerts}</strong>
            </div>
          )}
          {'datasetWindow' in data && (
            <div className="stat-mini">
              <span>Dataset window</span>
              <strong>{data.datasetWindow}</strong>
            </div>
          )}
        </div>

        {reportKey === 'daily' && 'topHotspots' in data && (
          <div className="mt-6 space-y-3">
            {data.topHotspots.map((item) => (
              <div key={item.name} className="list-row">
                <div>
                  <strong>{item.name}</strong>
                  <small>{item.violations} violations</small>
                </div>
                <div className="text-right">
                  <div className="font-semibold text-white">{item.riskScore.toFixed(1)}%</div>
                </div>
              </div>
            ))}
          </div>
        )}

        {reportKey === 'weekly' && 'trend' in data && (
          <div className="mt-6 space-y-3">
            {data.trend.map((item) => (
              <div key={item.date} className="list-row">
                <div>
                  <strong>{item.date}</strong>
                  <small>Daily trend</small>
                </div>
                <div className="font-semibold text-white">{item.violations}</div>
              </div>
            ))}
          </div>
        )}

        {reportKey === 'risk' && 'predictedHotspotsNext24h' in data && (
          <div className="mt-6 grid gap-3 md:grid-cols-2">
            {data.predictedHotspotsNext24h.map((item) => (
              <div key={item.name} className="panel-stat">
                <span className="muted-text">{item.name}</span>
                <strong>{item.predictedRisk.toFixed(1)}%</strong>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
